// ==UserScript==
// @name            Search Keyboard shortcuts
// @description     Lightweight script to add search and filter options in keyboard shortcuts in settings
// @author          Bibek Bhusal
// @version         1.1.6
// @lastUpdated     2026-10-09
// @ignorecache
// @homepage        https://github.com/Vertex-Mods/Search-Keyboard-Shortcuts
// @include         about:preferences*
// @include         about:settings*
// ==/UserScript==

// This file was automatically generated. Do not edit this file directly.
// Any changes made here will be overwritten.
// To make changes, please edit the source files in the repository:
// https://github.com/BibekBhusal0/zen-custom-js

(() => {

  // utils/parse.js
  var parseElement = (elementString, type = "html") => {
    if (type === "xul")
      return window.MozXULElement.parseXULToFragment(elementString).firstChild;
    let element = new DOMParser().parseFromString(elementString, "text/html");
    if (element.body.children.length)
      element = element.body.firstChild;
    else
      element = element.head.firstChild;
    return element;
  };

  // utils/fuzzy.js
  function calculateFuzzyScore(target, query) {
    if (!target || !query)
      return 0;
    let targetLower = target.toLowerCase(), queryLower = query.toLowerCase(), targetLen = target.length, queryLen = query.length;
    if (queryLen > targetLen)
      return 0;
    if (queryLen === 0)
      return 0;
    if (targetLower === queryLower)
      return 200;
    if (targetLower.startsWith(queryLower))
      return 100 + queryLen;
    if (targetLower.split(/[\s-_]+/).map((word) => word[0]).join("") === queryLower)
      return 90 + queryLen;
    let score = 0, queryIndex = 0, lastMatchIndex = -1, consecutiveMatches = 0;
    for (let targetIndex = 0;targetIndex < targetLen; targetIndex++)
      if (queryIndex < queryLen && targetLower[targetIndex] === queryLower[queryIndex]) {
        let bonus = 10;
        if (targetIndex === 0 || [" ", "-", "_"].includes(targetLower[targetIndex - 1]))
          bonus += 15;
        if (lastMatchIndex === targetIndex - 1)
          consecutiveMatches++, bonus += 20 * consecutiveMatches;
        else
          consecutiveMatches = 0;
        if (lastMatchIndex !== -1) {
          let distance = targetIndex - lastMatchIndex;
          bonus -= Math.min(distance - 1, 10);
        }
        score += bonus, lastMatchIndex = targetIndex, queryIndex++;
      }
    return queryIndex === queryLen ? score : 0;
  }
  function fuzzyScore(target, query) {
    let cleanQuery = (query || "").trim();
    if (!cleanQuery)
      return 1;
    return calculateFuzzyScore(target || "", cleanQuery);
  }

  // settings-shortcuts-search/index.js
  function _setupKeymapSearchUI(groupbox) {
    if (groupbox.querySelector(".zen-keyboard-controls"))
      return;
    let searchContainer = parseElement(`
    <div class="zen-keyboard-controls">
      <input placeholder="Search shortcuts..." class="zen-keyboard-search">
      <button class="zen-keyboard-filter-button">Filter</button>
    </div>
  `), searchInput = searchContainer.querySelector("input"), filterButton = searchContainer.querySelector("button"), firstHBox = groupbox.querySelector("hbox");
    if (firstHBox)
      groupbox.insertBefore(searchContainer, firstHBox);
    else
      groupbox.appendChild(searchContainer);
    let filterPopover = parseElement('<div class="zen-keyboard-filter-popover" style="display: none;"></div>');
    document.body.appendChild(filterPopover);
    let groupCheckboxes = {}, groupHeadings = groupbox.querySelectorAll("h2[data-group]");
    groupHeadings.forEach((h2) => {
      let groupId = h2.getAttribute("data-group"), label = h2.textContent.trim();
      if (label) {
        let wrapper = parseElement(`
        <label class="zen-keyboard-filter-checkbox">
          <input type="checkbox" data-group="${groupId}" checked>
          ${label}
        </label>
      `), checkbox = wrapper.querySelector("input");
        groupCheckboxes[groupId] = checkbox, filterPopover.appendChild(wrapper);
      }
    }), filterButton.addEventListener("click", () => {
      let rect = filterButton.getBoundingClientRect();
      filterPopover.style.top = `${rect.bottom + window.scrollY}px`, filterPopover.style.left = `${rect.left + window.scrollX}px`, filterPopover.style.display = filterPopover.style.display === "none" ? "flex" : "none";
    }), document.addEventListener("click", (e) => {
      if (!filterPopover.contains(e.target) && e.target !== filterButton)
        filterPopover.style.display = "none";
    });
    function applyFilters() {
      let searchValue = searchInput.value.trim(), visibleGroups = /* @__PURE__ */ new Set;
      for (let groupId in groupCheckboxes)
        if (groupCheckboxes[groupId].checked)
          visibleGroups.add(groupId.replace("zenCKSOption-group-", ""));
      groupbox.querySelectorAll("hbox.zenCKSOption").forEach((option) => {
        let input = option.querySelector(".zenCKSOption-input"), shortcutName = option.querySelector(".zenCKSOption-label")?.textContent || "", group = input?.getAttribute("data-group"), matchesSearch = fuzzyScore(shortcutName, searchValue) > 0, matchesGroup = visibleGroups.has(group);
        option.style.display = matchesSearch && matchesGroup ? "" : "none";
      }), groupHeadings.forEach((h2) => {
        let groupId = h2.getAttribute("data-group").replace("zenCKSOption-group-", ""), anyVisible = [
          ...groupbox.querySelectorAll(`.zenCKSOption-input[data-group="${groupId}"]`)
        ].some((input) => input.closest("hbox.zenCKSOption").style.display !== "none");
        h2.style.display = anyVisible ? "" : "none";
      });
    }
    searchInput.addEventListener("input", applyFilters), Object.values(groupCheckboxes).forEach((cb) => {
      cb.addEventListener("change", applyFilters);
    }), applyFilters();
  }
  function addSettingKeymapSearch() {
    let groupbox = document.getElementById("zenCKSGroup");
    if (!groupbox)
      return;
    if (groupbox.querySelector(".zen-keyboard-controls"))
      return;
    let checkAndSetup = () => {
      let groupHeadings = groupbox.querySelectorAll("h2[data-group]"), options = groupbox.querySelectorAll("hbox.zenCKSOption");
      if (Array.from(groupHeadings).some((h2) => h2.textContent.trim().length > 0) && options.length > 0)
        return _setupKeymapSearchUI(groupbox), !0;
      return !1;
    };
    if (checkAndSetup())
      return;
    new MutationObserver((mutations, observer) => {
      if (checkAndSetup())
        observer.disconnect();
    }).observe(groupbox, { childList: !0, subtree: !0 });
  }
  addSettingKeymapSearch();
  var observer = new MutationObserver((mutations) => {
    let groupboxAppeared = !1;
    for (let mutation of mutations)
      if (mutation.type === "childList") {
        if (Array.from(mutation.addedNodes).some((node) => node.nodeType === Node.ELEMENT_NODE && node.id === "zenCKSGroup")) {
          groupboxAppeared = !0;
          break;
        }
        if (Array.from(mutation.addedNodes).some((node) => node.nodeType === Node.ELEMENT_NODE && node.querySelector && node.querySelector("#zenCKSGroup"))) {
          groupboxAppeared = !0;
          break;
        }
      }
    if (groupboxAppeared)
      addSettingKeymapSearch();
  });
  observer.observe(document.body, { childList: !0, subtree: !0 });
})();
